In [1]:
import pandas as pd
import numpy as np
import pymysql
import sys
import static

les différentes tables à requêter :

ATTENTION : après chaque requête et avant d'en faire une nouvelle, il faut bien penser a fermer la connexion avec la bdd (sinon, ça ba buguer)

- aircraft
- flights_metrics
- flights_summary
- countries
- airports
- cities

In [2]:
# pour faire des requêtes sql

# connexion à la BDD

name_database = static.name_bdd
cnx = pymysql.connect(host = static.host, user = static.user, password = static.password)
cursor = cnx.cursor()
use_db = "use {name}".format(name = name_database)
cursor.execute(use_db)

#### Execute query ####

query1 = ("select * from COUNTRIES")
cursor.execute(query1)




#### Create dataframe from resultant table ####
frame = pd.DataFrame(cursor.fetchall())


# TJRS FERMER LA CONNEXION APR7S UNE REQUETE (SINON : Bug) !

cursor.close()
cnx.close()


frame

      0    1                     2
0    AD  AND               Andorra
1    AE  ARE  United Arab Emirates
2    AF  AFG           Afghanistan
3    AG  ATG   Antigua and Barbuda
4    AI  AIA              Anguilla
..   ..  ...                   ...
248  YE  YEM                 Yemen
249  YT  MYT               Mayotte
250  ZA  ZAF          South Africa
251  ZM  ZMB                Zambia
252  ZW  ZWE              Zimbabwe

[253 rows x 3 columns]

In [3]:
# pour faire des requêtes sql

# connexion à la BDD

name_database = static.name_bdd
cnx = pymysql.connect(host = static.host, user = static.user, password = static.password)
cursor = cnx.cursor()
use_db = "use {name}".format(name = name_database)
cursor.execute(use_db)


# test jointure entre toutes les tables

#### Execute query ####

query1 = ("(SELECT * from FLIGHTS_SUMMARY LEFT JOIN AIRCRAFT ON FLIGHTS_SUMMARY.hex = AIRCRAFT.hex LEFT JOIN FLIGHTS_METRICS ON AIRCRAFT.hex = FLIGHTS_METRICS.hex LEFT JOIN AIRPORTS a ON FLIGHTS_SUMMARY.dep_iata = a.iata_code  LEFT JOIN AIRPORTS b ON FLIGHTS_SUMMARY.arr_iata = b.iata_code LEFT JOIN COUNTRIES as c ON a.country_code = c.code LEFT JOIN COUNTRIES as d ON b.country_code = d.code)")
cursor.execute(query1)


#### Create dataframe from resultant table ####
frame = pd.DataFrame(cursor.fetchall())
pd.set_option("display.max_rows", None, "display.max_columns", None)

# TJRS FERMER LA CONNEXION APR7S UNE REQUETE (SINON : Bug) !

cursor.close()
cnx.close()


frame.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57
0,1,300738,DLH1656,LH1656,To be defined,DE,MUC,TSR,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,2022-08-16,0 days 15:36:00,no terminal,no terminal,To be defined,To be defined,300738,DLH,LH,E195,E95,EMBRAER,1,300738,DLH1656,LH1656,47.1026,17.91910,10210.0,109.0,837.0,-1.0,2022-08-16,0 days 15:36:00,MUC,EDDM,Munich International Airport,DE,48.35,11.79,TSR,LRTR,Timisoara Traian Vuia International Airport,RO,45.81,21.33,DE,DEU,Germany,RO,ROU,Romania
1,1,300738,DLH1656,LH1656,To be defined,DE,MUC,TSR,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,2022-08-16,0 days 15:36:00,no terminal,no terminal,To be defined,To be defined,300738,DLH,LH,E195,E95,EMBRAER,118,300738,DLH1656,LH1656,47.1026,17.91910,10210.0,109.0,837.0,-1.0,2022-08-16,0 days 15:51:00,MUC,EDDM,Munich International Airport,DE,48.35,11.79,TSR,LRTR,Timisoara Traian Vuia International Airport,RO,45.81,21.33,DE,DEU,Germany,RO,ROU,Romania
2,1,300738,DLH1656,LH1656,To be defined,DE,MUC,TSR,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,2022-08-16,0 days 15:36:00,no terminal,no terminal,To be defined,To be defined,300738,DLH,LH,E195,E95,EMBRAER,495,300738,DLH2382,LH2382,47.4266,8.22242,9136.0,247.0,681.0,-1.0,2022-08-17,0 days 09:08:00,MUC,EDDM,Munich International Airport,DE,48.35,11.79,TSR,LRTR,Timisoara Traian Vuia International Airport,RO,45.81,21.33,DE,DEU,Germany,RO,ROU,Romania
3,1,300738,DLH1656,LH1656,To be defined,DE,MUC,TSR,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,2022-08-16,0 days 15:36:00,no terminal,no terminal,To be defined,To be defined,300738,DLH,LH,E195,E95,EMBRAER,1086,300738,DLH2383,LH2383,47.8228,10.93930,4030.0,70.0,635.0,-1.0,2022-08-17,0 days 10:52:00,MUC,EDDM,Munich International Airport,DE,48.35,11.79,TSR,LRTR,Timisoara Traian Vuia International Airport,RO,45.81,21.33,DE,DEU,Germany,RO,ROU,Romania
4,1,300738,DLH1656,LH1656,To be defined,DE,MUC,TSR,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,1900-01-01,1900-01-01,0 days 00:01:00,0 days 00:01:00,2022-08-16,0 days 15:36:00,no terminal,no terminal,To be defined,To be defined,300738,DLH,LH,E195,E95,EMBRAER,1213,300738,DLH4XY,LH4XY,45.5245,9.07497,2903.0,216.0,516.0,-1.0,2022-09-07,0 days 16:49:00,MUC,EDDM,Munich International Airport,DE,48.35,11.79,TSR,LRTR,Timisoara Traian Vuia International Airport,RO,45.81,21.33,DE,DEU,Germany,RO,ROU,Romania

In [4]:
# A LANCER A CHAQUE FIN DE SESSION:

cursor.close()
cnx.close()

Error: Already closed